"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-07 18:46:02.920648

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edge_band_stock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("article", sa.String(length=100), nullable=False),
        sa.Column("thickness", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("decor", sa.String(length=200), nullable=False),
        sa.Column("length_meters_left", sa.Float(), nullable=False),
        sa.Column("supplier", sa.String(length=200), nullable=False),
        sa.Column("price_per_m", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("layer_signature", sa.JSON(), nullable=False),
        sa.Column("units", sa.String(length=8), nullable=True),
        sa.Column("dims_are", sa.String(length=16), nullable=False),
        sa.Column("one_file_one_part", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("article", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("nominal_thickness", sa.Float(), nullable=False),
        sa.Column("actual_thickness", sa.Float(), nullable=False),
        sa.Column("grain_matters", sa.Boolean(), nullable=False),
        sa.Column("default_sheet_w", sa.Float(), nullable=False),
        sa.Column("default_sheet_l", sa.Float(), nullable=False),
        sa.Column("supplier", sa.String(length=200), nullable=False),
        sa.Column("price_per_m2", sa.Float(), nullable=False),
        sa.Column("batch_code", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("customer", sa.String(length=200), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("diameter", sa.Float(), nullable=False),
        sa.Column("flutes", sa.Integer(), nullable=False),
        sa.Column("cutting_length", sa.Float(), nullable=False),
        sa.Column("shank_diameter", sa.Float(), nullable=False),
        sa.Column("max_plunge_depth", sa.Float(), nullable=False),
        sa.Column("in_atc", sa.Boolean(), nullable=False),
        sa.Column("atc_position", sa.Integer(), nullable=True),
        sa.Column("life_minutes", sa.Float(), nullable=False),
        sa.Column("used_minutes", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("thickness", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cutting_modes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tool_id", sa.Integer(), nullable=False),
        sa.Column("material_type", sa.String(length=32), nullable=False),
        sa.Column("thickness_from", sa.Float(), nullable=False),
        sa.Column("thickness_to", sa.Float(), nullable=False),
        sa.Column("operation_type", sa.String(length=32), nullable=False),
        sa.Column("rpm", sa.Integer(), nullable=False),
        sa.Column("feed_xy", sa.Float(), nullable=False),
        sa.Column("feed_z_plunge", sa.Float(), nullable=False),
        sa.Column("depth_per_pass", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("entry", sa.String(length=16), nullable=False),
        sa.Column("ramp_angle", sa.Float(), nullable=True),
        sa.Column("ramp_length", sa.Float(), nullable=True),
        sa.Column("lead_in_type", sa.String(length=16), nullable=False),
        sa.Column("lead_radius", sa.Float(), nullable=True),
        sa.Column("finish_pass", sa.Boolean(), nullable=False),
        sa.Column("finish_allowance", sa.Float(), nullable=False),
        sa.Column("stepover_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["tools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cutting_modes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cutting_modes_tool_id"), ["tool_id"], unique=False)

    op.create_table(
        "layer_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("layer_regex", sa.String(length=500), nullable=True),
        sa.Column("aci_color", sa.Integer(), nullable=True),
        sa.Column("rgb_color", sa.String(length=7), nullable=True),
        sa.Column("linetype", sa.String(length=100), nullable=True),
        sa.Column("block_name", sa.String(length=200), nullable=True),
        sa.Column("geom_closed", sa.String(length=8), nullable=False),
        sa.Column("diameter_from", sa.Float(), nullable=True),
        sa.Column("diameter_to", sa.Float(), nullable=True),
        sa.Column("area_from", sa.Float(), nullable=True),
        sa.Column("area_to", sa.Float(), nullable=True),
        sa.Column("operation_type", sa.String(length=32), nullable=False),
        sa.Column("depth", sa.Float(), nullable=True),
        sa.Column("depth_ref", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=1), nullable=False),
        sa.Column("extra_params", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["import_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("layer_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_layer_rules_profile_id"), ["profile_id"], unique=False)

    op.create_table(
        "parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("article", sa.String(length=100), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=True),
        sa.Column("thickness", sa.Float(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("outer_contour", sa.JSON(), nullable=False),
        sa.Column("inner_contours", sa.JSON(), nullable=False),
        sa.Column("grain", sa.String(length=8), nullable=False),
        sa.Column("edge_banding", sa.JSON(), nullable=False),
        sa.Column("dims_are", sa.String(length=16), nullable=False),
        sa.Column("edge_allowance", sa.JSON(), nullable=False),
        sa.Column("is_two_sided", sa.Boolean(), nullable=False),
        sa.Column("source_file", sa.String(length=500), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_parts_project_id"), ["project_id"], unique=False)

    op.create_table(
        "sheet_stock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("nominal_w", sa.Float(), nullable=False),
        sa.Column("nominal_l", sa.Float(), nullable=False),
        sa.Column("actual_w", sa.Float(), nullable=False),
        sa.Column("actual_l", sa.Float(), nullable=False),
        sa.Column("trim_allowance", sa.JSON(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("is_remnant", sa.Boolean(), nullable=False),
        sa.Column("remnant_code", sa.String(length=50), nullable=True),
        sa.Column("parent_sheet_id", sa.Integer(), nullable=True),
        sa.Column("polygon", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reserved_for_project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_sheet_id"],
            ["sheet_stock.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reserved_for_project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("remnant_code"),
    )
    with op.batch_alter_table("sheet_stock", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sheet_stock_material_id"), ["material_id"], unique=False
        )

    op.create_table(
        "nc_programs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("sheet_index", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=1), nullable=False),
        sa.Column("tool_number", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("gcode_path", sa.String(length=1000), nullable=False),
        sa.Column("estimated_seconds", sa.Float(), nullable=False),
        sa.Column("cut_length", sa.Float(), nullable=False),
        sa.Column("checks_passed", sa.Boolean(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("generated_by_user_id", sa.Integer(), nullable=True),
        sa.Column("exported_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nc_programs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nc_programs_batch_id"), ["batch_id"], unique=False)

    op.create_table(
        "nest_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("sheet_stock_id", sa.Integer(), nullable=False),
        sa.Column("sheet_index", sa.Integer(), nullable=False),
        sa.Column("placements", sa.JSON(), nullable=False),
        sa.Column("utilization_pct", sa.Float(), nullable=False),
        sa.Column("waste_area", sa.Float(), nullable=False),
        sa.Column("remnants", sa.JSON(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("progress", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sheet_stock_id"],
            ["sheet_stock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nest_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nest_results_batch_id"), ["batch_id"], unique=False)

    op.create_table(
        "operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("geometry", sa.JSON(), nullable=False),
        sa.Column("depth", sa.Float(), nullable=True),
        sa.Column("depth_ref", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=1), nullable=False),
        sa.Column("tool_override", sa.Integer(), nullable=True),
        sa.Column("mode_override", sa.Integer(), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("low_confidence", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mode_override"],
            ["cutting_modes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_override"],
            ["tools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("operations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_operations_part_id"), ["part_id"], unique=False)

    op.create_table(
        "part_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("index_in_batch", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("defect_reason", sa.Text(), nullable=False),
        sa.Column("reissued_from_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reissued_from_id"],
            ["part_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("part_instances", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_part_instances_batch_id"), ["batch_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_part_instances_part_id"), ["part_id"], unique=False)

    op.create_table(
        "stock_txns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("sheet_stock_id", sa.Integer(), nullable=True),
        sa.Column("edge_band_id", sa.Integer(), nullable=True),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("reverses_txn_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["edge_band_id"],
            ["edge_band_stock.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reverses_txn_id"],
            ["stock_txns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sheet_stock_id"],
            ["sheet_stock.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_txns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_txns_edge_band_id"), ["edge_band_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_txns_sheet_stock_id"), ["sheet_stock_id"], unique=False
        )

    op.create_table(
        "tech_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("material_type", sa.String(length=32), nullable=False),
        sa.Column("thickness_from", sa.Float(), nullable=False),
        sa.Column("thickness_to", sa.Float(), nullable=False),
        sa.Column("operation_type", sa.String(length=32), nullable=False),
        sa.Column("diameter_from", sa.Float(), nullable=False),
        sa.Column("diameter_to", sa.Float(), nullable=False),
        sa.Column("width_from", sa.Float(), nullable=False),
        sa.Column("width_to", sa.Float(), nullable=False),
        sa.Column("tool_id", sa.Integer(), nullable=False),
        sa.Column("mode_id", sa.Integer(), nullable=False),
        sa.Column("strategy_params", sa.JSON(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mode_id"],
            ["cutting_modes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["tools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tech_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tech_profiles_material_type"), ["material_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tech_profiles_operation_type"), ["operation_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tech_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tech_profiles_operation_type"))
        batch_op.drop_index(batch_op.f("ix_tech_profiles_material_type"))

    op.drop_table("tech_profiles")
    with op.batch_alter_table("stock_txns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_txns_sheet_stock_id"))
        batch_op.drop_index(batch_op.f("ix_stock_txns_edge_band_id"))

    op.drop_table("stock_txns")
    with op.batch_alter_table("part_instances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_part_instances_part_id"))
        batch_op.drop_index(batch_op.f("ix_part_instances_batch_id"))

    op.drop_table("part_instances")
    with op.batch_alter_table("operations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_operations_part_id"))

    op.drop_table("operations")
    with op.batch_alter_table("nest_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nest_results_batch_id"))

    op.drop_table("nest_results")
    with op.batch_alter_table("nc_programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nc_programs_batch_id"))

    op.drop_table("nc_programs")
    with op.batch_alter_table("sheet_stock", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sheet_stock_material_id"))

    op.drop_table("sheet_stock")
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parts_project_id"))

    op.drop_table("parts")
    with op.batch_alter_table("layer_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_layer_rules_profile_id"))

    op.drop_table("layer_rules")
    with op.batch_alter_table("cutting_modes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cutting_modes_tool_id"))

    op.drop_table("cutting_modes")
    op.drop_table("batches")
    op.drop_table("users")
    op.drop_table("tools")
    op.drop_table("projects")
    op.drop_table("materials")
    op.drop_table("import_profiles")
    op.drop_table("edge_band_stock")
    # ### end Alembic commands ###
